name: game
version: 0.1.0.0
homepage: 'https://github.com/githubuser/game#readme'
license: BSD3
author: Author name here
maintainer: example@example.com
copyright: 2020 Author name here
category: Web
extra-source-files:
  - README.md
dependencies:
  - base
  - apecs
  - apecs-physics
  - text
  - containers
  - sdl2
  - sdl2-image
  - sdl2-gfx
  - linear
  - vector
  - hashable
  - unordered-containers
  - hashtables
  - transformers
  - mtl
  - StateVar
  - binary
  - colour
  - pqueue
executables:
  game:
    source-dirs: src
    main: Main.hs
default-extensions:
  - OverloadedStrings
  - TypeFamilies
  - DataKinds
  - NamedFieldPuns
  - LambdaCase
  - TupleSections
  - GeneralizedNewtypeDeriving
  - DeriveGeneric
  - RankNTypes
  - FlexibleInstances
  - FlexibleContexts
  - MultiParamTypeClasses
  - GADTs
  - ScopedTypeVariables
  - TypeApplications
